version: '3.8'
services:
  db:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - '5432:5432'

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./prod.env
    depends_on:
      - db

volumes:
  postgres_data:
